unificar ejemplos con Geiger Counter
ElectronicCats/CatSatZero pull request #5
Opened 2019-02-27 20:49 UTC by sabas1080

He unificado los ejemplos de catsat zero basico con ejemplo de Geiger, con la intencion de no mantener dos skecth y tener que actualizar bugs en dos sketchs

Geiger se puede activar usando "#DEFINE GEIGER"

2019-03-01 20:38 UTC, sabas1080 commented
@wero1414

2019-03-02 00:38 UTC, wero1414 commented
Testing...

2019-03-02 00:58 UTC, wero1414 commented on Firmware/CaTSatZero/CaTSatZero.ino
> +  SerialUSB.println("GPS balloon mode configured");
```suggestion
  SerialUSB.println("GPS balloon mode configured");
```
Move it into the If statment

2019-03-02 01:00 UTC, wero1414 requested changes
Change the Debug actived by default option to merge :D

2019-03-02 18:05 UTC, wero1414 approved these changes
Great merge

2019-03-02 18:05 UTC, merged